oneup_flysystem:
    adapters:
        default_adapter:
            local:
                location: '%kernel.project_dir%/public/uploads/images/products'
        aws_adapter:
            awss3v3:
                client: aws.s3_client
                bucket: vich
                prefix: /vich
                options:
                    ACL: bucket-owner-full-control
    filesystems:
        default_filesystem:
            adapter: default_adapter
            mount: default_filesystem
        aws_filesystem:
            adapter: aws_adapter
            mount: aws_filesystem
            visibility: public
            directory_visibility: public
