vich_uploader:
    db_driver: orm
    twig: true

    mappings:
        products:
            uri_prefix: uploads/images/products
            upload_destination: '%kernel.project_dir%/public/uploads/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
